version: 0.0
os: linux


files:
  - source: /
    destination: /home/ubuntu/webapp


hooks:

  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 300
      runas: ubuntu