name: Build & Deploy application

env:
  ARTIFACT_NAME: webapp
  CODEDEPLOY_APPLICATION_NAME: mywebapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP: mywebapp
  AWS_REGION: us-east-1


on:
  push:
    branches: [ main ]

jobs:
    ci_cd:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install Node Dependecy
          run: npm ci
        
        - name: Build Node project
          run: npm run build --if-present
        
        - name: Test Node Checks
          run: npm test

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ${{ secrets.AWS_REGION }}
        
        - name: Build Deployment artifacts
          run: |
            mkdir codedeploy_artifact
            ls -al
            zip -r ${{ env.ARTIFACT_NAME }} dist package.json codedeploy/*.sh appspec.yml
            pwd
            ls -al
            mv ${{ env.ARTIFACT_NAME }}.* codedeploy_artifact
            ls -al
            pwd
            cd codedeploy_artifact
            pwd
            ls -al
            cd ..
            pwd
            ls -al


        - name: Copy Artifacts to S3
          run: |
            aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_CODEDEPLOY_BUCKET}}

        - name: Codeeploy API Call
          run: |
            output=$(aws deploy create-deployment \
              --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME }} \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name ${{ env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP }} \
              --description "CSYE6225 - CodeDeploy" \
              --s3-location bucket ${{ secrets.S3_CODEDEPLOY_BUCKET }},key=${{env.ARTIFACT_NAME}},bundleType=zip \
              --region ${{ env.AWS_REGION }}
              --output json)

              echo $output
              dId=$(echo $output | jq -r '.deploymentId')

              aws deploy wait deployment-successful --deployment-id $dId

