name: Build & Deploy application

env:
  ARTIFACT_NAME: webapp
  CODEDEPLOY_APPLICATION_NAME: webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP: csye6225-webapp-deployment
  AWS_REGION: us-east-1
  ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID}}
  SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

on:
  push:
    branches: [ main ]

jobs:
    ci:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: '14'

        - name: Install Node Dependecy
          run: npm ci
        
        - name: Build Node project
          run: npm run build --if-present
        
        - name: Test Cases Checks
          run: npm test


        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ${{ secrets.AWS_REGION }}
        
        - name: Build Deployment artifacts
          run: |
            mkdir codedeploy_artifact
            ls -al
            zip -r ${{ env.ARTIFACT_NAME }} package.json dist codedeploy/*.sh appspec.yml cloudwatch-config.json  tsconfig.json config tslint.json src package-lock.json logs
            pwd
            ls -al
            mv ${{ env.ARTIFACT_NAME }}.* codedeploy_artifact
            pwd
            cd codedeploy_artifact
            cd ..
            pwd
            ls -al

        - name: Copy Artifacts to S3
          run: |
            aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_CODEDEPLOY_BUCKET}}
        
    cd:
      runs-on: ubuntu-latest
      needs: ci
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ${{ secrets.AWS_REGION }}


        - name: Codedeploy API Call
          run: |
            output=$(aws deploy create-deployment \
              --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME }} \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name ${{ env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP }} \
              --description "CSYE6225 - CodeDeploy" \
              --s3-location bucket=${{ secrets.S3_CODEDEPLOY_BUCKET }},key=${{env.ARTIFACT_NAME}}.zip,bundleType=zip \
              --region ${{ env.AWS_REGION }} \
              --output json)

              echo $output
              
              dId=$(echo $output | jq -r '.deploymentId')
              aws deploy wait deployment-successful --deployment-id $dId

